import { type Product } from "@/components/catalog/product-card"

export const products: Product[] = [
  {
    id: "1",
    name: "Royal Blue Agbada with Gold Embroidery",
    category: "Agbada",
    gender: "Men",
    occasion: ["Wedding", "Festival", "Cultural"],
    fabric: "Guinea Brocade",
    startingPrice: 185000,
    image: "/images/products/agbada-royal-blue.jpg",
    badge: "Made to Measure",
  },
  {
    id: "2",
    name: "Vibrant Orange & Teal Ankara Dress",
    category: "Ankara",
    gender: "Women",
    occasion: ["Party", "Casual", "Cultural"],
    fabric: "Ankara (African Print)",
    startingPrice: 45000,
    image: "/images/products/ankara-dress-orange.jpg",
    badge: "Ready to Ship",
  },
  {
    id: "3",
    name: "White & Silver Embroidered Kaftan",
    category: "Kaftan",
    gender: "Men",
    occasion: ["Corporate", "Casual", "Cultural"],
    fabric: "Atiku",
    startingPrice: 75000,
    image: "/images/products/kaftan-white-silver.jpg",
    badge: "Made to Measure",
  },
  {
    id: "4",
    name: "Purple & Gold Aso-Oke Ensemble",
    category: "Aso-Oke",
    gender: "Women",
    occasion: ["Wedding", "Festival", "Cultural"],
    fabric: "Aso-Oke",
    startingPrice: 250000,
    image: "/images/products/aso-oke-purple.jpg",
    badge: "Made to Measure",
  },
  {
    id: "5",
    name: "Deep Green Senator Style",
    category: "Senator",
    gender: "Men",
    occasion: ["Corporate", "Casual", "Party"],
    fabric: "Jacquard",
    startingPrice: 95000,
    image: "/images/products/senator-green.jpg",
    badge: "Ready to Ship",
  },
  {
    id: "6",
    name: "Elegant Red & Gold Ankara Gown",
    category: "Ankara",
    gender: "Women",
    occasion: ["Wedding", "Party", "Festival"],
    fabric: "Ankara (African Print)",
    startingPrice: 68000,
    image: "/images/products/ankara-gown-red.jpg",
    badge: "Made to Measure",
  },
  {
    id: "7",
    name: "Colorful Kids Ankara Set",
    category: "Ankara",
    gender: "Kids",
    occasion: ["Casual", "Party", "Cultural"],
    fabric: "Ankara (African Print)",
    startingPrice: 25000,
    image: "/images/products/kids-ankara-set.jpg",
    badge: "Ready to Ship",
  },
  {
    id: "8",
    name: "Brown & Gold Wedding Agbada",
    category: "Agbada",
    gender: "Men",
    occasion: ["Wedding", "Festival"],
    fabric: "Guinea Brocade",
    startingPrice: 220000,
    image: "/images/products/agbada-brown-gold.jpg",
    badge: "Made to Measure",
  },
]
